#!/bin/sh
# Color definitions (taken from Color Bash Prompt HowTo).
# Some colors might look different of some terminals.
# For example, I see 'Bold Red' as 'orange' on my screen,
# hence the 'Green' 'BRed' 'Red' sequence I often use in my prompt.


# Normal Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

NC="\e[0m"               # Color Reset


branch=$(\git branch | sed -n -e 's/^\* \(.*\)/\1/p')
branch=$(echo "$branch" | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g')

if [ -z $branch ]
then
	exit 1
fi

COLOR="BGreen";
branch=$(printf ${!COLOR}$branch${NC})
MSG=$(printf " ${BRed} Are you sure that you want to create new branch starting from ${branch} ${BRed} ? (Y/n) ${NC}")
MSG2=$(printf " ${BRed} Aborted!\n ${NC}")

if [[ $branch == *"dev"* ]] && [ $# -eq 2 ] && [ -n $2 ] 
then
	# Allows us to read user input below, assigns stdin to keyboard
	exec < /dev/tty

	while true; do
	  read -p "${MSG}" yn
	  if [ "$yn" = "" ]; then
		yn='n'
	  fi
	  case $yn in
		  [Yy] ) break;;
		  [Nn] ) echo ${MSG2}; exit 1;;
		  * ) printf "Please answer y or n for yes or no.\n";;
	  esac
	done
fi
printf "${NC}"
